version: "2"
services:
    mongodb:
        image: "abulo/docker-mongodb:latest"
        container_name: mongodb
        hostname: mongodb
        environment:
            - AUTH=yes
            - MONGODB_ADMIN_USER=admin
            - MONGODB_ADMIN_PASS=admin123
            - MONGODB_APPLICATION_DATABASE=logs
            - MONGODB_APPLICATION_USER=abulo
            - MONGODB_APPLICATION_PASS=abulo123
        ports:
            - "37017:27017"
        networks:
            abulo:
                ipv4_address: 172.18.1.2
        ulimits:
            nproc: 1048576
        hostname: mongodb
        mem_limit: 512m
        restart: always
        volumes:
            - ./Docker/data/mongodb/:/data/db
            - ./Docker/config/hosts:/etc/hosts:ro
    mysql:
        image: "abulo/docker-mysql:latest"
        container_name: mysql
        hostname: mysql
        ports:
            - "33061:3306"
        networks:
            abulo:
                ipv4_address: 172.18.1.3
        ulimits:
            nproc: 65535
        hostname: mysql
        mem_limit: 512m
        restart: always
        volumes:
            - ./Docker/config/mysql/:/etc/mysql/:ro
            - ./Docker/config/hosts:/etc/hosts:ro
            - ./Docker/data/mysql/:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysql
    #redis
    redis:
        image: "redis:latest"
        container_name: redis
        hostname: redis
        ports:
            - "63790:6379"
        networks:
            abulo:
                ipv4_address: 172.18.1.4
        ulimits:
            nproc: 65535
        hostname: redis
        mem_limit: 512m
        restart: always
        volumes:
            - ./Docker/config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
            - ./Docker/config/hosts:/etc/hosts:ro
    #consul
    consul:
        image: consul
        container_name: consul
        hostname: consul
        command: agent -ui -client 0.0.0.0 -server -bootstrap-expect 1
        ports:
            - "18500:8500"
        networks:
            abulo:
                ipv4_address: 172.18.1.5
        volumes:
            - ./Docker/config/hosts:/etc/hosts:ro
    swoole1:
        image: "abulo/docker-php:latest"
        container_name: swoole1
        ports:
            - "9091:9091"
            - "8081:8081"
            - "8083:8083"
            - "9999:9999"
            - "18000:18000"
            - "18083:18083"
        networks:
            abulo:
                ipv4_address: 172.18.1.6
        ulimits:
            nproc: 65535
        hostname: swoole1
        mem_limit: 512m
        environment:
            SD_NODE_NAME: "SD-1"
        depends_on:
            - mongodb
            - mysql
            - redis
            - consul
        volumes:
            - ./Docker/config/php/php.ini:/usr/local/php/etc/php.ini:ro
            - ./Docker/config/hosts:/etc/hosts:ro
            - ./Kernel:/home/www/Kernel
            - ./Webroot:/home/www/Webroot
            - ./bin:/home/www/bin
        links:
            - mongodb
            - mysql
            - redis
            - consul
        command: ["php","/home/www/Webroot/launch/http.php","start"]
    swoole2:
        image: "abulo/docker-php:latest"
        container_name: swoole2
        ports:
            - "29091:9091"
            - "28081:8081"
            - "38083:8083"
            - "29999:9999"
            - "28000:18000"
            - "28083:18083"
        networks:
            abulo:
                ipv4_address: 172.18.1.7
        ulimits:
            nproc: 65535
        hostname: swoole2
        mem_limit: 512m
        environment:
            SD_NODE_NAME: "SD-2"
        depends_on:
            - mongodb
            - mysql
            - redis
            - consul
        volumes:
            - ./Docker/config/php/php.ini:/usr/local/php/etc/php.ini:ro
            - ./Docker/config/hosts:/etc/hosts:ro
            - ./Kernel:/home/www/Kernel
            - ./Webroot:/home/www/Webroot
            - ./bin:/home/www/bin
        links:
            - mongodb
            - mysql
            - redis
            - consul
        command: ["php","/home/www/Webroot/launch/http.php","start"]
networks:
    abulo:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
                - subnet: 172.18.1.0/24
                  gateway: 172.18.1.1
