version: "2"
services:
    mongodb:
        image: "abulo/docker-mongodb:latest"
        container_name: mongodb
        environment:
            - AUTH=yes
            - MONGODB_ADMIN_USER=admin
            - MONGODB_ADMIN_PASS=admin123
            - MONGODB_APPLICATION_DATABASE=logs
            - MONGODB_APPLICATION_USER=abulo
            - MONGODB_APPLICATION_PASS=abulo123
        ports:
            - "37017:27017"
        networks:
            abulo:
                ipv4_address: 172.18.1.2
        ulimits:
            nproc: 1048576
        hostname: mongodb
        mem_limit: 512m
        restart: always
        volumes:
            - ./Docker/data/mongodb/:/data/db
            - ./Docker/config/hosts:/etc/hosts:ro
    swoole:
        image: "abulo/docker-php:latest"
        container_name: swoole
        ports:
            - "60080:60080"
        networks:
            abulo:
                ipv4_address: 172.18.1.5
        ulimits:
            nproc: 65535
        hostname: swoole
        mem_limit: 512m
        depends_on:
            - mongodb
        volumes:
            - ./Docker/config/php/php.ini:/usr/local/php/etc/php.ini:ro
            - ./Docker/config/hosts:/etc/hosts:ro
            - ./Docker/config/pool/pool.ini:/etc/pool.ini:ro
            - ./Kernel:/home/www/Kernel
            - ./Webroot:/home/www/Webroot
        links:
            - mongodb
        command: ["php","/home/www/Webroot/launch/http.php","start"]

networks:
    abulo:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
                - subnet: 172.18.1.0/24
                  gateway: 172.18.1.1
